//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutenticacionesWSAA
    {
        public int IdAutenticacion { get; set; }
        public string Token { get; set; }
        public string Sign { get; set; }
        public System.DateTime FechaAutorizacion { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public byte IdEmpresa { get; set; }
    }
}
