//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraArchivoFact
    {
        public short IdTipoDocumento { get; set; }
        public string TipoF { get; set; }
        public Nullable<decimal> Dto { get; set; }
        public string Observaciones { get; set; }
        public string FPago { get; set; }
        public string RazonSocial { get; set; }
        public string TipoDoc { get; set; }
        public Nullable<int> NroDoc { get; set; }
        public string RegImp { get; set; }
        public string Direccion { get; set; }
        public int IdFacturaVenta { get; set; }
    }
}
