//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaMediosPagos
    {
        public int IdCajaMedioPago { get; set; }
        public int IdCajaDiaria { get; set; }
        public decimal Monto { get; set; }
        public short IdTipoPago { get; set; }
    
        public virtual CajasDiarias CajasDiarias { get; set; }
        public virtual TiposPagos TiposPagos { get; set; }
    }
}
