//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajasEgresos
    {
        public int IdCajaEgreso { get; set; }
        public int IdCajaDiaria { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> Usuario { get; set; }
    
        public virtual CajasDiarias CajasDiarias { get; set; }
    }
}
