//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajasMovimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajasMovimientos()
        {
            this.CajasMovimientosDetalle = new HashSet<CajasMovimientosDetalle>();
        }
    
        public long IdMovimientoCaja { get; set; }
        public int IdAperturaCaja { get; set; }
        public short IdTipoMovCaja { get; set; }
        public decimal Monto { get; set; }
        public Nullable<decimal> VueltoEntregado { get; set; }
        public Nullable<int> IdFacturaVenta { get; set; }
        public string DescripcionMov { get; set; }
        public System.DateTime FechaMov { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string UsrAcceso { get; set; }
        public System.DateTime FechaAcceso { get; set; }
    
        public virtual CajasAperturas CajasAperturas { get; set; }
        public virtual TiposMovimientosCaja TiposMovimientosCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CajasMovimientosDetalle> CajasMovimientosDetalle { get; set; }
    }
}
