//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajasAperturasDetalle
    {
        public int IdAperturaDetalle { get; set; }
        public int IdApertura { get; set; }
        public short SencilloInicio5ctvos { get; set; }
        public short SencilloInicio10ctvos { get; set; }
        public short SencilloInicio25ctvos { get; set; }
        public short SencilloInicio50ctvos { get; set; }
        public short SencilloInicio1peso { get; set; }
        public short SencilloInicio2pesos { get; set; }
        public short SencilloInicio5pesos { get; set; }
        public short SencilloInicio10pesos { get; set; }
        public short SencilloInicio20pesos { get; set; }
        public short SencilloInicio50pesos { get; set; }
        public short SencilloInicio100pesos { get; set; }
        public short SencilloCierre5ctvos { get; set; }
        public short SencilloCierre10ctvos { get; set; }
        public short SencilloCierre25ctvos { get; set; }
        public short SencilloCierre50ctvos { get; set; }
        public short SencilloCierre1peso { get; set; }
        public short SencilloCierre2pesos { get; set; }
        public short SencilloCierre5pesos { get; set; }
        public short SencilloCierre10pesos { get; set; }
        public short SencilloCierre20pesos { get; set; }
        public short SencilloCierre50pesos { get; set; }
        public short SencilloCierre100pesos { get; set; }
    }
}
