//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculoStockInicial
    {
        public long IdArticulo { get; set; }
        public double StockActual { get; set; }
        public decimal Restar { get; set; }
        public decimal sumar { get; set; }
        public double StockInicial { get; set; }
        public string Fecha { get; set; }
    }
}
