//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelacionFacturas
    {
        public int IdCancelacion { get; set; }
        public int IdRecibo { get; set; }
        public int IdFacturaVenta { get; set; }
        public decimal MontoCancelacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> IdNotaCredito { get; set; }
        public Nullable<int> NroCliente { get; set; }
    }
}
