//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cheques()
        {
            this.CajasMovimientosDetalle = new HashSet<CajasMovimientosDetalle>();
            this.PagosDetalle = new HashSet<PagosDetalle>();
            this.RecibosDetalle = new HashSet<RecibosDetalle>();
        }
    
        public int IdCheque { get; set; }
        public long NroCheque { get; set; }
        public decimal MontoCheque { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int IdBanco { get; set; }
        public System.DateTime FechaCobro { get; set; }
        public Nullable<bool> Cruzado { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string UsrAcceso { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public bool Propio { get; set; }
        public short IdEmpresa { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CajasMovimientosDetalle> CajasMovimientosDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosDetalle> PagosDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosDetalle> RecibosDetalle { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
