//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CierresIvaCompras
    {
        public int IdCierre { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public int MesCorrespondiente { get; set; }
        public int AñoCorrespondiente { get; set; }
    }
}
