//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesCajasDistribucionesServiciosEstados
    {
        public int ClienteCajaDistribucionServicioEstadoId { get; set; }
        public int ClienteCajaDistribucionServicioId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public short UsuarioUltimaModificacion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ClientesCajasDistribucionesServicios ClientesCajasDistribucionesServicios { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
