//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesCajasDistribucionesServicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesCajasDistribucionesServicios()
        {
            this.ClientesCajasDistribucionesServiciosEstados = new HashSet<ClientesCajasDistribucionesServiciosEstados>();
            this.FacturasVenta = new HashSet<FacturasVenta>();
        }
    
        public int ClienteCajaDistribucionServicioId { get; set; }
        public int ClienteId { get; set; }
        public int CajaDistribucionId { get; set; }
        public int ServicioId { get; set; }
        public Nullable<int> UltimoEstadoId { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public short UsuarioUltimaModificacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServiciosEstados> ClientesCajasDistribucionesServiciosEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasVenta> FacturasVenta { get; set; }
    }
}
