//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.ClientesCajasDistribucionesServicios = new HashSet<ClientesCajasDistribucionesServicios>();
            this.DatosImpositivos = new HashSet<DatosImpositivos>();
            this.Presupuestos = new HashSet<Presupuestos>();
            this.Remitos = new HashSet<Remitos>();
        }
    
        public int NroCliente { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<int> NroDocumento { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Direccion { get; set; }
        public short CodigoPostal { get; set; }
        public byte SubCodigoPostal { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public short IdRegimenImpositivo { get; set; }
        public string Telefono { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Cuit0 { get; set; }
        public string Cuit1 { get; set; }
        public string Cuit2 { get; set; }
        public string UsrBaja { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<System.DateTime> FechaAcceso { get; set; }
        public string UsrAcceso { get; set; }
        public Nullable<byte> IdObservación { get; set; }
        public string MensajeCuenta { get; set; }
        public Nullable<decimal> SaldoExcedido { get; set; }
        public string CuentaCerrada { get; set; }
        public string Comentario { get; set; }
        public string Precinto { get; set; }
        public string Caja { get; set; }
    
        public virtual CPostales CPostales { get; set; }
        public virtual RegimenesImpositivos RegimenesImpositivos { get; set; }
        public virtual TiposDocumento TiposDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServicios> ClientesCajasDistribucionesServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosImpositivos> DatosImpositivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presupuestos> Presupuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remitos> Remitos { get; set; }
    }
}
