//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosImpositivos
    {
        public int IdDatosImpositivos { get; set; }
        public int NroCliente { get; set; }
        public short IdTipoImpuesto { get; set; }
        public Nullable<System.DateTime> FechaInicioExc { get; set; }
        public Nullable<byte> IdProvincia { get; set; }
        public int NroInscripcion { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public string NroCertificadoExc { get; set; }
        public Nullable<System.DateTime> FechaFinExc { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public string UsrAcceso { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual TiposImpuestos TiposImpuestos { get; set; }
    }
}
