//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleArchivoFact
    {
        public string Articulo { get; set; }
        public string UMedida { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public float IVA { get; set; }
        public int IdFacturaVenta { get; set; }
    }
}
