//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.AsientosContables = new HashSet<AsientosContables>();
            this.Cheques = new HashSet<Cheques>();
            this.ControladoresFiscales = new HashSet<ControladoresFiscales>();
            this.FacturasCompra = new HashSet<FacturasCompra>();
            this.Pagos = new HashSet<Pagos>();
            this.Presupuestos = new HashSet<Presupuestos>();
            this.Recibos = new HashSet<Recibos>();
            this.Remitos = new HashSet<Remitos>();
            this.RemitosCompra = new HashSet<RemitosCompra>();
            this.FacturasVenta = new HashSet<FacturasVenta>();
        }
    
        public short IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string NFantasia { get; set; }
        public Nullable<System.DateTime> InicioActividades { get; set; }
        public string CUIT { get; set; }
        public byte[] Logo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string IIBB { get; set; }
        public string CondicionIva { get; set; }
        public Nullable<short> CodigoPostal { get; set; }
        public Nullable<byte> SubCodigoPostal { get; set; }
        public string RutaCertificado { get; set; }
        public string SerialCertificado { get; set; }
        public string CuitParaImpresion { get; set; }
        public string IIBBParaImpresion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosContables> AsientosContables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheques> Cheques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControladoresFiscales> ControladoresFiscales { get; set; }
        public virtual CPostales CPostales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasCompra> FacturasCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presupuestos> Presupuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibos> Recibos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remitos> Remitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemitosCompra> RemitosCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasVenta> FacturasVenta { get; set; }
    }
}
