//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores
    {
        public long IdError { get; set; }
        public string TextoError { get; set; }
        public string UsrError { get; set; }
        public string SeccionError { get; set; }
        public string ObjetoError { get; set; }
        public string TraceError { get; set; }
        public System.DateTime FechaError { get; set; }
    }
}
