//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasCompra()
        {
            this.FacturasCompraDetalle = new HashSet<FacturasCompraDetalle>();
        }
    
        public int IdFacturaCompra { get; set; }
        public short IdTipoDocumento { get; set; }
        public short IdTipoFactura { get; set; }
        public string BVFactCompra { get; set; }
        public string NCompFactCompra { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public short IdFormaPago { get; set; }
        public Nullable<short> IdCondicionPago { get; set; }
        public int NroProveedor { get; set; }
        public string Observaciones { get; set; }
        public decimal Subtotal105 { get; set; }
        public decimal Subtotal21 { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Bonificacion1 { get; set; }
        public decimal TotalBonificacion1 { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public decimal Bonificacion2 { get; set; }
        public decimal Bonificacion3 { get; set; }
        public decimal Bonificacion4 { get; set; }
        public decimal PorcentajePerIVA { get; set; }
        public decimal PorcentajePerIIBB { get; set; }
        public decimal TotalBonificacion2 { get; set; }
        public decimal TotalBonificacion3 { get; set; }
        public decimal TotalBonificacion4 { get; set; }
        public decimal TotalDescuento105 { get; set; }
        public decimal TotalDescuento21 { get; set; }
        public decimal TotalPerIVA { get; set; }
        public decimal TotalPerIIBB { get; set; }
        public decimal TotalIVA105 { get; set; }
        public decimal TotalIVA21 { get; set; }
        public short IdEmpresa { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public string UsrAcceso { get; set; }
        public int AñoCorrespondiente { get; set; }
        public int MesCorrespondiente { get; set; }
        public decimal ConceptosNoGravados { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string BVFactReferencia { get; set; }
        public string NCompFactReferencia { get; set; }
        public decimal Bonificacion5 { get; set; }
        public decimal Bonificacion6 { get; set; }
        public decimal TotalBonificacion5 { get; set; }
        public decimal TotalBonificacion6 { get; set; }
        public decimal SubTotal27 { get; set; }
        public decimal TotalDescuento27 { get; set; }
        public decimal TotalIVA27 { get; set; }
    
        public virtual CondicionesPago CondicionesPago { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual TiposDocFact TiposDocFact { get; set; }
        public virtual TiposFactura TiposFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasCompraDetalle> FacturasCompraDetalle { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
