//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasElectronicas
    {
        public int IdFacturaElectronica { get; set; }
        public Nullable<int> IdFacturaVenta { get; set; }
        public string CAE { get; set; }
        public System.DateTime FechaVtoCAE { get; set; }
        public string NCompFact { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
