//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneracionInteres
    {
        public long IdGeneracionInteres { get; set; }
        public int IdDiaGeneracion { get; set; }
        public int IdFacturaVenta { get; set; }
        public short NroGeneracion { get; set; }
        public decimal TotalInteres { get; set; }
    
        public virtual DiaGeneracionInteres DiaGeneracionInteres { get; set; }
        public virtual FacturasVenta FacturasVenta { get; set; }
    }
}
