//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidacionesFacturas
    {
        public int IdLiquidacionFacturas { get; set; }
        public int IdFacturaVenta { get; set; }
        public int IdLiquidacion { get; set; }
        public decimal MontoBase { get; set; }
        public decimal MontoComision { get; set; }
        public Nullable<int> IdRecibo { get; set; }
        public Nullable<long> IdMovCaja { get; set; }
    
        public virtual Liquidaciones Liquidaciones { get; set; }
    }
}
