//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SgPymeBaseEntities : DbContext
    {
        public SgPymeBaseEntities()
            : base("name=SgPymeBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AjustesStock> AjustesStock { get; set; }
        public virtual DbSet<ArchivosGenerados> ArchivosGenerados { get; set; }
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<AsientosContables> AsientosContables { get; set; }
        public virtual DbSet<AutenticacionesWSAA> AutenticacionesWSAA { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<Cajas> Cajas { get; set; }
        public virtual DbSet<CajasAperturas> CajasAperturas { get; set; }
        public virtual DbSet<CajasAperturasDetalle> CajasAperturasDetalle { get; set; }
        public virtual DbSet<CajasDistribuciones> CajasDistribuciones { get; set; }
        public virtual DbSet<CajasMovimientos> CajasMovimientos { get; set; }
        public virtual DbSet<CajasMovimientosDetalle> CajasMovimientosDetalle { get; set; }
        public virtual DbSet<CancelacionFacturas> CancelacionFacturas { get; set; }
        public virtual DbSet<CancelacionFacturasCompra> CancelacionFacturasCompra { get; set; }
        public virtual DbSet<Cheques> Cheques { get; set; }
        public virtual DbSet<CierresIvaCompras> CierresIvaCompras { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ClientesCajasDistribucionesServicios> ClientesCajasDistribucionesServicios { get; set; }
        public virtual DbSet<ClientesCajasDistribucionesServiciosEstados> ClientesCajasDistribucionesServiciosEstados { get; set; }
        public virtual DbSet<CondicionesPago> CondicionesPago { get; set; }
        public virtual DbSet<ControladoresFiscales> ControladoresFiscales { get; set; }
        public virtual DbSet<CPostales> CPostales { get; set; }
        public virtual DbSet<CuentasBancarias> CuentasBancarias { get; set; }
        public virtual DbSet<CuentasContables> CuentasContables { get; set; }
        public virtual DbSet<DatosImpositivos> DatosImpositivos { get; set; }
        public virtual DbSet<Depositos> Depositos { get; set; }
        public virtual DbSet<DiaGeneracionInteres> DiaGeneracionInteres { get; set; }
        public virtual DbSet<EmpTarjetas> EmpTarjetas { get; set; }
        public virtual DbSet<Errores> Errores { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<EstadosCaja> EstadosCaja { get; set; }
        public virtual DbSet<FacturasCompra> FacturasCompra { get; set; }
        public virtual DbSet<FacturasCompraDetalle> FacturasCompraDetalle { get; set; }
        public virtual DbSet<FacturasElectronicas> FacturasElectronicas { get; set; }
        public virtual DbSet<FacturasVentaDetalle> FacturasVentaDetalle { get; set; }
        public virtual DbSet<FormasPago> FormasPago { get; set; }
        public virtual DbSet<GeneracionInteres> GeneracionInteres { get; set; }
        public virtual DbSet<Liquidaciones> Liquidaciones { get; set; }
        public virtual DbSet<LiquidacionesFacturas> LiquidacionesFacturas { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<MovimientosBancos> MovimientosBancos { get; set; }
        public virtual DbSet<MovimientosDepositos> MovimientosDepositos { get; set; }
        public virtual DbSet<ObservacionesCliente> ObservacionesCliente { get; set; }
        public virtual DbSet<OrdenesPedidoFacturas> OrdenesPedidoFacturas { get; set; }
        public virtual DbSet<OrdenesPedidos> OrdenesPedidos { get; set; }
        public virtual DbSet<OrdenesPedidosDetalle> OrdenesPedidosDetalle { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<PagosDetalle> PagosDetalle { get; set; }
        public virtual DbSet<PeriodosContables> PeriodosContables { get; set; }
        public virtual DbSet<PreciosVenta> PreciosVenta { get; set; }
        public virtual DbSet<Presupuestos> Presupuestos { get; set; }
        public virtual DbSet<PresupuestosDetalles> PresupuestosDetalles { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Recibos> Recibos { get; set; }
        public virtual DbSet<RecibosDetalle> RecibosDetalle { get; set; }
        public virtual DbSet<ReferentesProveedores> ReferentesProveedores { get; set; }
        public virtual DbSet<RegimenesImpositivos> RegimenesImpositivos { get; set; }
        public virtual DbSet<Remitos> Remitos { get; set; }
        public virtual DbSet<RemitosCompra> RemitosCompra { get; set; }
        public virtual DbSet<RemitosDetalle> RemitosDetalle { get; set; }
        public virtual DbSet<RemitosDetalleCompra> RemitosDetalleCompra { get; set; }
        public virtual DbSet<RemitosXfacturados> RemitosXfacturados { get; set; }
        public virtual DbSet<RetencionesGcia> RetencionesGcia { get; set; }
        public virtual DbSet<Rubros> Rubros { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Seteos> Seteos { get; set; }
        public virtual DbSet<SubRubros> SubRubros { get; set; }
        public virtual DbSet<TiposCF> TiposCF { get; set; }
        public virtual DbSet<TiposCheques> TiposCheques { get; set; }
        public virtual DbSet<TiposConceptoFactura> TiposConceptoFactura { get; set; }
        public virtual DbSet<TiposDocFact> TiposDocFact { get; set; }
        public virtual DbSet<TiposDocumento> TiposDocumento { get; set; }
        public virtual DbSet<TiposFactura> TiposFactura { get; set; }
        public virtual DbSet<TiposImpuestos> TiposImpuestos { get; set; }
        public virtual DbSet<TiposIva> TiposIva { get; set; }
        public virtual DbSet<TiposMovimientosBanco> TiposMovimientosBanco { get; set; }
        public virtual DbSet<TiposMovimientosCaja> TiposMovimientosCaja { get; set; }
        public virtual DbSet<TiposMovimientosDepositos> TiposMovimientosDepositos { get; set; }
        public virtual DbSet<TiposPagos> TiposPagos { get; set; }
        public virtual DbSet<TiposPersona> TiposPersona { get; set; }
        public virtual DbSet<TiposRetenciones> TiposRetenciones { get; set; }
        public virtual DbSet<TiposUsuarios> TiposUsuarios { get; set; }
        public virtual DbSet<TiposVendedores> TiposVendedores { get; set; }
        public virtual DbSet<TiposVendedoresExternos> TiposVendedoresExternos { get; set; }
        public virtual DbSet<UnidadesMedida> UnidadesMedida { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vendedores> Vendedores { get; set; }
        public virtual DbSet<VendedoresFacturasVenta> VendedoresFacturasVenta { get; set; }
        public virtual DbSet<VendedoresRemitos> VendedoresRemitos { get; set; }
        public virtual DbSet<CabeceraArchivoFact> CabeceraArchivoFact { get; set; }
        public virtual DbSet<CalculoStockInicial> CalculoStockInicial { get; set; }
        public virtual DbSet<DetalleArchivoFact> DetalleArchivoFact { get; set; }
        public virtual DbSet<FechaServidor> FechaServidor { get; set; }
        public virtual DbSet<VistaAperturasCajas> VistaAperturasCajas { get; set; }
        public virtual DbSet<VistaArticulos> VistaArticulos { get; set; }
        public virtual DbSet<VistaArticulosPV> VistaArticulosPV { get; set; }
        public virtual DbSet<VistaArtSinVentas> VistaArtSinVentas { get; set; }
        public virtual DbSet<VistaAsientosContables> VistaAsientosContables { get; set; }
        public virtual DbSet<VistaCabeceraRemImp> VistaCabeceraRemImp { get; set; }
        public virtual DbSet<VistaCabFactCompra> VistaCabFactCompra { get; set; }
        public virtual DbSet<VistaCabFactVenta> VistaCabFactVenta { get; set; }
        public virtual DbSet<VistaCabFactVentaConCaja> VistaCabFactVentaConCaja { get; set; }
        public virtual DbSet<VistaCajaDistribuciones> VistaCajaDistribuciones { get; set; }
        public virtual DbSet<VistaCajas> VistaCajas { get; set; }
        public virtual DbSet<VistaCancelacionFacturas> VistaCancelacionFacturas { get; set; }
        public virtual DbSet<VistaCancelacionFacturasRetenciones> VistaCancelacionFacturasRetenciones { get; set; }
        public virtual DbSet<VistaCancelacionNC> VistaCancelacionNC { get; set; }
        public virtual DbSet<VistaCancelacionNCPagos> VistaCancelacionNCPagos { get; set; }
        public virtual DbSet<VistaCantFactporRubro> VistaCantFactporRubro { get; set; }
        public virtual DbSet<VistaCantFactporRubroSubRubro> VistaCantFactporRubroSubRubro { get; set; }
        public virtual DbSet<VistaCantFactporSubRubro> VistaCantFactporSubRubro { get; set; }
        public virtual DbSet<VistaCCClientesME> VistaCCClientesME { get; set; }
        public virtual DbSet<VistaCCProveedoresME> VistaCCProveedoresME { get; set; }
        public virtual DbSet<VistaCFs> VistaCFs { get; set; }
        public virtual DbSet<VistaCheques> VistaCheques { get; set; }
        public virtual DbSet<VistaChequesPropios> VistaChequesPropios { get; set; }
        public virtual DbSet<VistaCobranzaxTP> VistaCobranzaxTP { get; set; }
        public virtual DbSet<VistaComprobantesSinSaldar> VistaComprobantesSinSaldar { get; set; }
        public virtual DbSet<VistaConsultaDetalleFacturacion> VistaConsultaDetalleFacturacion { get; set; }
        public virtual DbSet<VistaConsultaDetalleFacturacionCompra> VistaConsultaDetalleFacturacionCompra { get; set; }
        public virtual DbSet<VistaCPostales> VistaCPostales { get; set; }
        public virtual DbSet<VistaCtaCteClientes> VistaCtaCteClientes { get; set; }
        public virtual DbSet<VistaCtaCteProveedores> VistaCtaCteProveedores { get; set; }
        public virtual DbSet<VistaCuentasBancarias> VistaCuentasBancarias { get; set; }
        public virtual DbSet<VistaDatosImpositivos> VistaDatosImpositivos { get; set; }
        public virtual DbSet<VistaDetalleAsientosContables> VistaDetalleAsientosContables { get; set; }
        public virtual DbSet<VistaDetalleCCClientes> VistaDetalleCCClientes { get; set; }
        public virtual DbSet<VistaDetalleCCProv> VistaDetalleCCProv { get; set; }
        public virtual DbSet<VistaDetalleFactCompra> VistaDetalleFactCompra { get; set; }
        public virtual DbSet<VistaDetalleFacturasSinComisionar> VistaDetalleFacturasSinComisionar { get; set; }
        public virtual DbSet<VistaDetalleFactVenta> VistaDetalleFactVenta { get; set; }
        public virtual DbSet<VistaDetalleMovimientosCajaySencillo> VistaDetalleMovimientosCajaySencillo { get; set; }
        public virtual DbSet<VistaDetalleMovimientosDepositos> VistaDetalleMovimientosDepositos { get; set; }
        public virtual DbSet<VistaDetallePagoCancelacion> VistaDetallePagoCancelacion { get; set; }
        public virtual DbSet<VistaDetalleReciboCancelacion> VistaDetalleReciboCancelacion { get; set; }
        public virtual DbSet<VistaDiaGeneracionIntereses> VistaDiaGeneracionIntereses { get; set; }
        public virtual DbSet<VistaEmpresa> VistaEmpresa { get; set; }
        public virtual DbSet<VistaFacturasSinSaldar> VistaFacturasSinSaldar { get; set; }
        public virtual DbSet<VistaFacturasSinSaldarCompras> VistaFacturasSinSaldarCompras { get; set; }
        public virtual DbSet<VistaLibroIvaCompras> VistaLibroIvaCompras { get; set; }
        public virtual DbSet<VistaLibroIvaVenta> VistaLibroIvaVenta { get; set; }
        public virtual DbSet<VistaMovimientosCaja> VistaMovimientosCaja { get; set; }
        public virtual DbSet<VistaMovimientosDepositos> VistaMovimientosDepositos { get; set; }
        public virtual DbSet<VistaMovStock> VistaMovStock { get; set; }
        public virtual DbSet<VistaNCCompSinSaldar> VistaNCCompSinSaldar { get; set; }
        public virtual DbSet<VistaNCsinSaldar> VistaNCsinSaldar { get; set; }
        public virtual DbSet<VistaOrdenesPedidoDetallePendienteFacturacion> VistaOrdenesPedidoDetallePendienteFacturacion { get; set; }
        public virtual DbSet<VistaOrdenesPedidos> VistaOrdenesPedidos { get; set; }
        public virtual DbSet<VistaOrdenesPedidosDetalle> VistaOrdenesPedidosDetalle { get; set; }
        public virtual DbSet<VistaPagos> VistaPagos { get; set; }
        public virtual DbSet<VistaPagosDetalle> VistaPagosDetalle { get; set; }
        public virtual DbSet<VistaPagosxTP> VistaPagosxTP { get; set; }
        public virtual DbSet<VistaPreciosVenta> VistaPreciosVenta { get; set; }
        public virtual DbSet<VistaPresupuestos> VistaPresupuestos { get; set; }
        public virtual DbSet<VistaPresupuestosDetalles> VistaPresupuestosDetalles { get; set; }
        public virtual DbSet<VistaProveedores> VistaProveedores { get; set; }
        public virtual DbSet<VistaProvVSArt> VistaProvVSArt { get; set; }
        public virtual DbSet<VistaRecibos> VistaRecibos { get; set; }
        public virtual DbSet<VistaRecibosDetalle> VistaRecibosDetalle { get; set; }
        public virtual DbSet<VistaRegimenesImpositivosCompras> VistaRegimenesImpositivosCompras { get; set; }
        public virtual DbSet<VistaRemitosCab> VistaRemitosCab { get; set; }
        public virtual DbSet<VistaRemitosCompraCab> VistaRemitosCompraCab { get; set; }
        public virtual DbSet<VistaRemitosCompraDet> VistaRemitosCompraDet { get; set; }
        public virtual DbSet<VistaRemitosDet> VistaRemitosDet { get; set; }
        public virtual DbSet<VistaRemitosnofactdeProv> VistaRemitosnofactdeProv { get; set; }
        public virtual DbSet<VistaRemitosXSinFacturar> VistaRemitosXSinFacturar { get; set; }
        public virtual DbSet<VistaStockArticulos> VistaStockArticulos { get; set; }
        public virtual DbSet<VistaTotalesCancelacionCobros> VistaTotalesCancelacionCobros { get; set; }
        public virtual DbSet<VistaTotalesCancelacionPagos> VistaTotalesCancelacionPagos { get; set; }
        public virtual DbSet<VistaTotalesComisionesFacturas> VistaTotalesComisionesFacturas { get; set; }
        public virtual DbSet<VistaTotalesDiscriminadosFactB> VistaTotalesDiscriminadosFactB { get; set; }
        public virtual DbSet<VistaTotalesDiscriminadosFactBCompra> VistaTotalesDiscriminadosFactBCompra { get; set; }
        public virtual DbSet<VistaTotalesNotaCredito> VistaTotalesNotaCredito { get; set; }
        public virtual DbSet<VistaTotalesNotaCreditoCompra> VistaTotalesNotaCreditoCompra { get; set; }
        public virtual DbSet<VistaTotalesRetenciones> VistaTotalesRetenciones { get; set; }
        public virtual DbSet<VistaTotalFPagosCaja> VistaTotalFPagosCaja { get; set; }
        public virtual DbSet<VistaUsuarios> VistaUsuarios { get; set; }
        public virtual DbSet<VistaVendedores> VistaVendedores { get; set; }
        public virtual DbSet<VistaVendedoresFactVta> VistaVendedoresFactVta { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<FacturasVenta> FacturasVenta { get; set; }
        public virtual DbSet<ReportePresupuesto> ReportePresupuesto { get; set; }
        public virtual DbSet<VistaClientes> VistaClientes { get; set; }
        public virtual DbSet<Ultima_Revision_Deudores> Ultima_Revision_Deudores { get; set; }
        public virtual DbSet<ClientesSuspendidos> ClientesSuspendidos { get; set; }
        public virtual DbSet<CajaMediosPagos> CajaMediosPagos { get; set; }
        public virtual DbSet<CajasDiarias> CajasDiarias { get; set; }
        public virtual DbSet<CajasEgresos> CajasEgresos { get; set; }
        public virtual DbSet<CajasIngresos> CajasIngresos { get; set; }
    
        [DbFunction("SgPymeBaseEntities", "FnBuscarEstadosPorClienteId")]
        public virtual IQueryable<FnBuscarEstadosPorClienteId_Result> FnBuscarEstadosPorClienteId(Nullable<int> clienteCajaDistribucionServicioId)
        {
            var clienteCajaDistribucionServicioIdParameter = clienteCajaDistribucionServicioId.HasValue ?
                new ObjectParameter("ClienteCajaDistribucionServicioId", clienteCajaDistribucionServicioId) :
                new ObjectParameter("ClienteCajaDistribucionServicioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FnBuscarEstadosPorClienteId_Result>("[SgPymeBaseEntities].[FnBuscarEstadosPorClienteId](@ClienteCajaDistribucionServicioId)", clienteCajaDistribucionServicioIdParameter);
        }
    
        public virtual ObjectResult<sp_ListaDeudores_Result> sp_ListaDeudores(Nullable<short> tipoDoc, Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta)
        {
            var tipoDocParameter = tipoDoc.HasValue ?
                new ObjectParameter("TipoDoc", tipoDoc) :
                new ObjectParameter("TipoDoc", typeof(short));
    
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("FechaDesde", fechaDesde) :
                new ObjectParameter("FechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("FechaHasta", fechaHasta) :
                new ObjectParameter("FechaHasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaDeudores_Result>("sp_ListaDeudores", tipoDocParameter, fechaDesdeParameter, fechaHastaParameter);
        }
    
        public virtual ObjectResult<sp_MovimientosStockPorFecha_Result> sp_MovimientosStockPorFecha(Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta)
        {
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("FechaDesde", fechaDesde) :
                new ObjectParameter("FechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("FechaHasta", fechaHasta) :
                new ObjectParameter("FechaHasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MovimientosStockPorFecha_Result>("sp_MovimientosStockPorFecha", fechaDesdeParameter, fechaHastaParameter);
        }
    }
}
