//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosDepositos
    {
        public long IdMovimientoDeposito { get; set; }
        public int IdDeposito { get; set; }
        public long IdArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public int IdTipoMovDeposito { get; set; }
        public Nullable<int> IdDepositoSecundario { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
    }
}
