//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesPedidosDetalle
    {
        public long IdOrdenDetalle { get; set; }
        public int IdOrdenPedido { get; set; }
        public Nullable<long> IdArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public System.DateTime FechaLinea { get; set; }
        public decimal Precio { get; set; }
        public string Artículo { get; set; }
        public string UMedida { get; set; }
        public byte IdTipoIva { get; set; }
        public string CodigoProducto { get; set; }
    
        public virtual OrdenesPedidos OrdenesPedidos { get; set; }
    }
}
