//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesPedidoFacturas
    {
        public long IdOrdenFactura { get; set; }
        public long IdOrdenDetalle { get; set; }
        public long IdFacturaCompraDetalle { get; set; }
        public decimal Cantidad { get; set; }
        public long IdArticulo { get; set; }
    }
}
