//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreciosVenta
    {
        public long IdArticulo { get; set; }
        public System.DateTime FechaPrecios { get; set; }
        public decimal PrecioContado { get; set; }
        public decimal PrecioFiado { get; set; }
        public Nullable<decimal> PrecioEspecial { get; set; }
        public decimal PrecioContadoIva { get; set; }
        public decimal PrecioFiadoIva { get; set; }
        public Nullable<decimal> PrecioEspecialIva { get; set; }
        public decimal PrecioBase { get; set; }
        public Nullable<decimal> Bonificacion1 { get; set; }
        public Nullable<decimal> Bonificacion2 { get; set; }
        public Nullable<decimal> Bonificacion3 { get; set; }
        public Nullable<decimal> Bonificacion4 { get; set; }
        public byte IdTipoIva { get; set; }
        public Nullable<decimal> CostoBruto { get; set; }
        public Nullable<decimal> PorcentajeFlete { get; set; }
        public Nullable<decimal> CostoFlete { get; set; }
        public Nullable<decimal> PorcentajeDescarga { get; set; }
        public Nullable<decimal> CostoDescarga { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public decimal PorcentajeGcia { get; set; }
        public Nullable<decimal> PorcentajeFiado { get; set; }
        public string UsrAcceso { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
    
        public virtual Articulos Articulos { get; set; }
    }
}
