//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.FacturasCompra = new HashSet<FacturasCompra>();
            this.OrdenesPedidos = new HashSet<OrdenesPedidos>();
            this.Pagos = new HashSet<Pagos>();
            this.ReferentesProveedores = new HashSet<ReferentesProveedores>();
            this.RemitosCompra = new HashSet<RemitosCompra>();
        }
    
        public int NroProveedor { get; set; }
        public string TipoDocumento { get; set; }
        public long NroDocumento { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Direccion { get; set; }
        public short CodigoPostal { get; set; }
        public byte SubCodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string PaginaWeb { get; set; }
        public Nullable<System.DateTime> FechaAcceso { get; set; }
        public string UsrAcceso { get; set; }
        public short IdRegimenImpositivo { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual CPostales CPostales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasCompra> FacturasCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesPedidos> OrdenesPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual TiposDocumento TiposDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferentesProveedores> ReferentesProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemitosCompra> RemitosCompra { get; set; }
    }
}
