//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosDetalle
    {
        public long IdReciboDetalle { get; set; }
        public short IdTipoPago { get; set; }
        public Nullable<int> IdCheque { get; set; }
        public int IdRecibo { get; set; }
        public decimal Monto { get; set; }
        public Nullable<short> IdEmpTarjeta { get; set; }
        public string NroTarjeta { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public string UsrAcceso { get; set; }
    
        public virtual Cheques Cheques { get; set; }
        public virtual EmpTarjetas EmpTarjetas { get; set; }
        public virtual Recibos Recibos { get; set; }
        public virtual TiposPagos TiposPagos { get; set; }
    }
}
