//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitosCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemitosCompra()
        {
            this.RemitosDetalleCompra = new HashSet<RemitosDetalleCompra>();
        }
    
        public int IdRemitoCompra { get; set; }
        public string BVRemCompra { get; set; }
        public string NroCompRemCompra { get; set; }
        public int NroProveedor { get; set; }
        public System.DateTime FechaRemitoCompra { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdFacturaCompra { get; set; }
        public short IdEmpresa { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public string UsrAcceso { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemitosDetalleCompra> RemitosDetalleCompra { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
