//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemitosDetalle
    {
        public long IdRemitoDetalle { get; set; }
        public int IdRemito { get; set; }
        public Nullable<long> IdArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public System.DateTime FechaLinea { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public string UsrAcceso { get; set; }
        public string Articulo { get; set; }
        public string UMedida { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
        public Nullable<bool> MueveStock { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Remitos Remitos { get; set; }
    }
}
