//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportePresupuesto
    {
        public int IdReporte { get; set; }
        public string Servicio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CantMeses { get; set; }
        public decimal Precio { get; set; }
        public string CondPago { get; set; }
        public string Observacion { get; set; }
        public string NombreSolicit { get; set; }
        public string Direccion { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
