//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicios()
        {
            this.ClientesCajasDistribucionesServicios = new HashSet<ClientesCajasDistribucionesServicios>();
            this.FacturasVentaDetalle = new HashSet<FacturasVentaDetalle>();
        }
    
        public int ServicioId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
        public short UsuarioUltimaModificacion { get; set; }
        public decimal Costo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string TipoServicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServicios> ClientesCajasDistribucionesServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasVentaDetalle> FacturasVentaDetalle { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
