//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seteos
    {
        public byte IdSeteo { get; set; }
        public bool UsarCF { get; set; }
        public byte DiasVtoFact { get; set; }
        public string PathBackUp { get; set; }
        public Nullable<decimal> PorcentajeGcia { get; set; }
        public Nullable<decimal> PorcentajeFiado { get; set; }
        public bool UsarCaja { get; set; }
        public bool UsarPrecioIVAPres { get; set; }
        public bool UsarCajaRegistradora { get; set; }
        public bool DuplicadoRecibo { get; set; }
        public bool UsarMultiEmpresa { get; set; }
        public bool MostrarArtBajas { get; set; }
        public bool MostrarCliBajas { get; set; }
        public bool MostarArtLoad { get; set; }
        public bool MostarArtPreciosLoad { get; set; }
        public bool FacturacionRapida { get; set; }
        public bool Usar4DigitosPrecios { get; set; }
        public bool UsarIntereses { get; set; }
        public Nullable<decimal> PorcentajeInteres { get; set; }
        public bool PreciosSoloAdmin { get; set; }
        public bool UsarRemitoX { get; set; }
        public bool ImprimirRecCtdoCajas { get; set; }
        public bool UsarDetalleCajas { get; set; }
        public bool UsarUpdater { get; set; }
        public bool UsarCB { get; set; }
        public bool UsarDolar { get; set; }
        public Nullable<decimal> CotizacionDolar { get; set; }
        public bool UsarLogo { get; set; }
        public bool DuplicadoRemitoX { get; set; }
        public bool Hollistor { get; set; }
        public bool Flete { get; set; }
        public bool Descarga { get; set; }
        public Nullable<decimal> PorcentajeFlete { get; set; }
        public Nullable<decimal> PorcentajeDescarga { get; set; }
        public bool Impuesto { get; set; }
        public Nullable<bool> HabilitarUserPorIntentos { get; set; }
        public Nullable<int> MaxIntentosFallidos { get; set; }
        public Nullable<int> LapsoTiempoBloqueo { get; set; }
        public bool PermitirFacturar { get; set; }
        public Nullable<System.DateTime> UltimaHoraZ { get; set; }
        public Nullable<decimal> ToleranciaDiferencia { get; set; }
    }
}
