//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.ClientesCajasDistribucionesServicios = new HashSet<ClientesCajasDistribucionesServicios>();
            this.ClientesCajasDistribucionesServicios1 = new HashSet<ClientesCajasDistribucionesServicios>();
            this.ClientesCajasDistribucionesServiciosEstados = new HashSet<ClientesCajasDistribucionesServiciosEstados>();
            this.Servicios = new HashSet<Servicios>();
        }
    
        public short IdUser { get; set; }
        public string NombreUser { get; set; }
        public short IdTipoUser { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public byte[] PassUser { get; set; }
        public Nullable<System.DateTime> FechaDeBloqueo { get; set; }
        public Nullable<int> NumeroDeIntentos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServicios> ClientesCajasDistribucionesServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServicios> ClientesCajasDistribucionesServicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesCajasDistribucionesServiciosEstados> ClientesCajasDistribucionesServiciosEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios> Servicios { get; set; }
        public virtual TiposUsuarios TiposUsuarios { get; set; }
    }
}
