//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaEmpresa
    {
        public string RazonSocial { get; set; }
        public string NFantasia { get; set; }
        public Nullable<System.DateTime> InicioActividades { get; set; }
        public string CUIT { get; set; }
        public byte[] Logo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string IIBB { get; set; }
        public string CondicionIva { get; set; }
        public string Localidad { get; set; }
        public short IdEmpresa { get; set; }
    }
}
