//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDetalleReciboCancelacion
    {
        public int IdCancelacion { get; set; }
        public int IdRecibo { get; set; }
        public int IdFacturaVenta { get; set; }
        public int NroCliente { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> TotalSaldado { get; set; }
        public decimal MontoCancelacion { get; set; }
        public System.DateTime FechaRecibo { get; set; }
        public Nullable<int> IdNotaCredito { get; set; }
        public string BVFact { get; set; }
        public string NCompFact { get; set; }
        public System.DateTime FechaFactura { get; set; }
    }
}
