//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaAperturasCajas
    {
        public int IdAperturaCaja { get; set; }
        public string FechaApertura { get; set; }
        public string UsrApertura { get; set; }
        public string Caja { get; set; }
        public decimal SaldoInicial { get; set; }
        public string SaldoFinal { get; set; }
        public string FechaCierre { get; set; }
        public string Estado { get; set; }
    }
}
