//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaConsultaDetalleFacturacionCompra
    {
        public int IdFacturaCompra { get; set; }
        public long IdFacturaCompraDetalle { get; set; }
        public string NroFactura { get; set; }
        public string FechaEmision { get; set; }
        public string DescCorta { get; set; }
        public Nullable<float> PrecioUnitario { get; set; }
        public decimal Cantidad { get; set; }
        public float PorcentajeIVA { get; set; }
        public Nullable<float> TotalArt { get; set; }
        public int NroProveedor { get; set; }
        public string ApellidoyNombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public short IdEmpresa { get; set; }
    }
}
