//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaTotalesDiscriminadosFactBCompra
    {
        public int IdFacturaCompra { get; set; }
        public Nullable<double> TotalGravado { get; set; }
        public Nullable<decimal> TotalNOGravado { get; set; }
        public Nullable<double> IVA21 { get; set; }
        public Nullable<double> IVA27 { get; set; }
        public Nullable<double> IVA105 { get; set; }
        public decimal TotalPerIIBB { get; set; }
        public decimal TotalPerIVA { get; set; }
        public decimal Total { get; set; }
    }
}
