//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCFs
    {
        public short IdCF { get; set; }
        public string BocadeVenta { get; set; }
        public string Observaciones { get; set; }
        public string TipoCF { get; set; }
        public string DescCF { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public short IdEmpresa { get; set; }
        public short Puerto { get; set; }
        public string MachineName { get; set; }
        public short IdTipoCF { get; set; }
    }
}
