//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaVendedores
    {
        public int NroVendedor { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<long> NroDocumento { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Direccion { get; set; }
        public short CodigoPostal { get; set; }
        public byte SubCodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string PaginaWeb { get; set; }
        public decimal PorcComision { get; set; }
        public int IdTipoVendedor { get; set; }
        public string Localidad { get; set; }
        public string TipoVendedor { get; set; }
        public Nullable<int> IdTipoVendedorExt { get; set; }
        public string TipoVendedorExterno { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    }
}
