//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaUsuarios
    {
        public short IdUser { get; set; }
        public string NombreUser { get; set; }
        public byte[] PassUser { get; set; }
        public string Tipo { get; set; }
        public string FechaBaja { get; set; }
        public short IdTipoUser { get; set; }
    }
}
