//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRecibos
    {
        public int IdRecibo { get; set; }
        public string ApellidoyNombre { get; set; }
        public int NroCliente { get; set; }
        public string FechaEmision { get; set; }
        public decimal MontoTotal { get; set; }
        public string FechaBaja { get; set; }
        public string Concepto { get; set; }
        public System.DateTime Fecha { get; set; }
        public short IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
    }
}
