//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRemitosCab
    {
        public int IdRemito { get; set; }
        public string NroRemito { get; set; }
        public string FechaRemito { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Observaciones { get; set; }
        public string NroFactura { get; set; }
        public int NroCliente { get; set; }
        public string DireccionCliente { get; set; }
        public string LocalidadCliente { get; set; }
        public string CondIvaCliente { get; set; }
        public short IdEmpresa { get; set; }
        public string FechaAnulacion { get; set; }
    }
}
