//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaStockArticulos
    {
        public long Nro_Art { get; set; }
        public string Artículo { get; set; }
        public double StockActual { get; set; }
        public double CantidadMinima { get; set; }
        public string U_Medida { get; set; }
        public string UltAct { get; set; }
    }
}
