//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRegimenesImpositivosCompras
    {
        public short IdRegimenImpositivo { get; set; }
        public string RegimenImpositivo { get; set; }
        public string Fecha { get; set; }
        public Nullable<decimal> NoGravado { get; set; }
        public Nullable<double> NetoGravado { get; set; }
        public Nullable<double> Iva105 { get; set; }
        public Nullable<double> Iva21 { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
