//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDetalleAsientosContables
    {
        public System.DateTime Fecha { get; set; }
        public long IdAsientoContable { get; set; }
        public int Periodo { get; set; }
        public string Tipo { get; set; }
        public decimal Valor { get; set; }
        public string NroCuenta { get; set; }
        public string CuentaContable { get; set; }
        public int IdCuentaContable { get; set; }
    }
}
