//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaOrdenesPedidoDetallePendienteFacturacion
    {
        public int IdOrdenPedido { get; set; }
        public long IdOrdenDetalle { get; set; }
        public Nullable<long> IdArticulo { get; set; }
        public string DescCorta { get; set; }
        public string NroOrden { get; set; }
        public int NroProveedor { get; set; }
        public string ApellidoyNombre { get; set; }
        public decimal TotalFacturado { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> PendienteFacturacion { get; set; }
    }
}
