//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaLibroIvaVenta
    {
        public string TipoDoc { get; set; }
        public string LetraFact { get; set; }
        public int IdFacturaVenta { get; set; }
        public string NroFactura { get; set; }
        public string FechaEmision { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Descripcion { get; set; }
        public string TipoDocumento { get; set; }
        public string NroDocumento { get; set; }
        public Nullable<double> NetoGravado { get; set; }
        public Nullable<decimal> NoGravado { get; set; }
        public Nullable<double> Iva105 { get; set; }
        public Nullable<double> Iva21 { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public short IdEmpresa { get; set; }
        public short IdRegimenImpositivo { get; set; }
        public bool Impresa { get; set; }
        public string Observaciones { get; set; }
    }
}
