//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCancelacionFacturasRetenciones
    {
        public int IdCancelacion { get; set; }
        public int IdPago { get; set; }
        public int IdFacturaCompra { get; set; }
        public decimal MontoCancelacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> IdNotaCredito { get; set; }
        public Nullable<long> IdMovBanco { get; set; }
        public int NroProveedor { get; set; }
        public string ApellidoyNombre { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public short IdEmpresa { get; set; }
        public decimal Subtotal { get; set; }
    }
}
