//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaArticulos
    {
        public long IdArticulo { get; set; }
        public string DescCorta { get; set; }
        public string DescLarga { get; set; }
        public string LlevarStock { get; set; }
        public string Stock { get; set; }
        public System.DateTime UltimaActStock { get; set; }
        public double CantidadMinima { get; set; }
        public string FechaBaja { get; set; }
        public string Rubro { get; set; }
        public string SubRubro { get; set; }
        public string UnidadMedida { get; set; }
        public string UsrBaja { get; set; }
        public double StockActual { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<System.DateTime> Maxfecha { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public int IdRubro { get; set; }
        public int IdSubRubro { get; set; }
        public string CodigoProducto { get; set; }
    }
}
