//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCajaDistribuciones
    {
        public int CajaDistribucionId { get; set; }
        public string Descipcion { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaUltimaModificacion { get; set; }
    }
}
