//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCPostales
    {
        public short CodigoPostal { get; set; }
        public byte SubCodigoPostal { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public string CpSubCp { get; set; }
        public byte IdProvincia { get; set; }
    }
}
