//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCabFactCompra
    {
        public int IdFacturaCompra { get; set; }
        public string TipoFact { get; set; }
        public string NroFact { get; set; }
        public string FechaEmision { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public decimal Subtotal { get; set; }
        public string Proveedor { get; set; }
        public decimal Total { get; set; }
        public string TipoDoc { get; set; }
        public string CondPago { get; set; }
        public string FPago { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string FechaAnulacion { get; set; }
        public int NroProveedor { get; set; }
        public decimal Bonificacion1 { get; set; }
        public decimal TotalBonificacion1 { get; set; }
        public decimal Bonificacion2 { get; set; }
        public decimal Bonificacion3 { get; set; }
        public decimal Bonificacion4 { get; set; }
        public decimal PorcentajePerIVA { get; set; }
        public decimal PorcentajePerIIBB { get; set; }
        public decimal TotalBonificacion2 { get; set; }
        public decimal TotalBonificacion3 { get; set; }
        public decimal TotalBonificacion4 { get; set; }
        public decimal TotalPerIVA { get; set; }
        public decimal TotalPerIIBB { get; set; }
        public decimal TotalIVA105 { get; set; }
        public decimal TotalIVA21 { get; set; }
        public decimal Subtotal105 { get; set; }
        public decimal Subtotal21 { get; set; }
        public decimal TotalDescuento105 { get; set; }
        public decimal TotalDescuento21 { get; set; }
        public string NroFactReferencia { get; set; }
        public short IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public short IdTipoDocumento { get; set; }
        public string BVFactCompra { get; set; }
        public string NCompFactCompra { get; set; }
        public string UsrAcceso { get; set; }
        public int AñoCorrespondiente { get; set; }
        public int MesCorrespondiente { get; set; }
        public decimal ConceptosNoGravados { get; set; }
        public decimal SubTotal27 { get; set; }
        public decimal TotalDescuento27 { get; set; }
        public decimal TotalIVA27 { get; set; }
    }
}
