//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPresupuestos
    {
        public int NroPresupuesto { get; set; }
        public string Fecha { get; set; }
        public string NombrePres { get; set; }
        public string Cliente { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> NroCliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> TotalDto { get; set; }
        public string Direccion { get; set; }
        public string FormaPago { get; set; }
        public string Observaciones { get; set; }
        public string PlazoEntrega { get; set; }
        public string Telefono { get; set; }
        public string ValidezOferta { get; set; }
        public short IdEmpresa { get; set; }
        public Nullable<int> IdFacturaVenta { get; set; }
    }
}
