//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDetalleFacturasSinComisionar
    {
        public string NroFactura { get; set; }
        public int IdFacturaVenta { get; set; }
        public long IdFacturaVentaDetalle { get; set; }
        public long IdArticulo { get; set; }
        public string Articulo { get; set; }
        public decimal PorcComision { get; set; }
        public decimal MontoComision { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int NroVendedor { get; set; }
    }
}
