//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaTotalFPagosCaja
    {
        public Nullable<decimal> Total { get; set; }
        public string FPago { get; set; }
        public int IdAperturaCaja { get; set; }
        public string DescripcionMov { get; set; }
        public string NroFact { get; set; }
        public short IdTipoMovCaja { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    }
}
