//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPagosDetalle
    {
        public int IdPago { get; set; }
        public decimal Monto { get; set; }
        public string TipoPago { get; set; }
        public long IdPagoDetalle { get; set; }
        public string NroCheque { get; set; }
    }
}
