//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaArticulosPV
    {
        public long IdArticulo { get; set; }
        public string Articulo { get; set; }
        public string FechaPrecio { get; set; }
        public decimal PrecioContado { get; set; }
        public decimal PrecioContadoIva { get; set; }
        public decimal PrecioFiado { get; set; }
        public decimal PrecioFiadoIva { get; set; }
        public decimal PrecioEspecial { get; set; }
        public decimal PrecioEspecialIva { get; set; }
        public decimal PrecioBase { get; set; }
        public string Rubro { get; set; }
        public string SubRubro { get; set; }
        public int IdRubro { get; set; }
        public int IdSubRubro { get; set; }
        public string CodigoBarra { get; set; }
        public string FechaBaja { get; set; }
        public string UMedida { get; set; }
        public double StockActual { get; set; }
        public Nullable<byte> Embalaje { get; set; }
    }
}
