//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDetalleFactCompra
    {
        public long IdFacturaCompraDetalle { get; set; }
        public int IdFacturaCompra { get; set; }
        public string DescCorta { get; set; }
        public string UMedida { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal TotalArt { get; set; }
        public bool DesdeRemito { get; set; }
        public Nullable<long> IdArticulo { get; set; }
        public float PorcentajeIVA { get; set; }
        public int NroProveedor { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
    }
}
