//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCabFactVenta
    {
        public string TipoDoc { get; set; }
        public int IdFacturaVenta { get; set; }
        public string TipoFact { get; set; }
        public string NroFact { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Pagado { get; set; }
        public string Impresa { get; set; }
        public string Observaciones { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal TotalDescuento { get; set; }
        public string Cliente { get; set; }
        public decimal Total { get; set; }
        public string CondPago { get; set; }
        public string FPago { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string FechaAnulacion { get; set; }
        public int NroCliente { get; set; }
        public string BVFact { get; set; }
        public decimal TotalIva105 { get; set; }
        public decimal TotalIva21 { get; set; }
        public short IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public decimal TotalSaldado { get; set; }
        public decimal TotalInteres { get; set; }
        public decimal TotalSaldadoInteres { get; set; }
        public string NroFactReferencia { get; set; }
        public int IdConceptoFactura { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Cobrador { get; set; }
        public string MesAbonado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
    }
}
