//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCabeceraRemImp
    {
        public string NroRemito { get; set; }
        public System.DateTime FechaRemito { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string TipoIVA { get; set; }
        public string Observaciones { get; set; }
        public int IdRemito { get; set; }
        public short IdEmpresa { get; set; }
    }
}
