//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDetalleMovimientosDepositos
    {
        public System.DateTime FechaMovimiento { get; set; }
        public string Deposito { get; set; }
        public Nullable<int> IdDeposito { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<int> IdTipoMovDeposito { get; set; }
        public Nullable<decimal> Ingreso { get; set; }
        public Nullable<decimal> Egreso { get; set; }
        public string DepositoSecundario { get; set; }
        public Nullable<int> IdDepositoSecundario { get; set; }
        public Nullable<long> IdArticulo { get; set; }
        public string DescCorta { get; set; }
    }
}
