//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaProvVSArt
    {
        public long IdArticulo { get; set; }
        public string DescCorta { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaUltPrecio { get; set; }
        public decimal PrecioUnitario { get; set; }
        public string Descripcion { get; set; }
        public int NroProveedor { get; set; }
        public string ApellidoyNombre { get; set; }
    }
}
