//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCobranzaxTP
    {
        public decimal Monto { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Descripcion { get; set; }
        public short IdEmpresa { get; set; }
    }
}
