//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaOrdenesPedidos
    {
        public int IdOrdenPedido { get; set; }
        public string NroOrden { get; set; }
        public System.DateTime FechaOrden { get; set; }
        public string Observaciones { get; set; }
        public int NroProveedor { get; set; }
        public string ApellidoyNombre { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public decimal Total { get; set; }
        public int Facturado { get; set; }
    }
}
