//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDetalleCCClientes
    {
        public string Documento { get; set; }
        public string NroComprobante { get; set; }
        public string Fecha { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public int Id { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public short IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public int Cobrador { get; set; }
    }
}
