//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRecibosDetalle
    {
        public long IdReciboDetalle { get; set; }
        public string TipoPago { get; set; }
        public decimal Monto { get; set; }
        public string NroCheque { get; set; }
        public int IdRecibo { get; set; }
        public string Empresa { get; set; }
        public string NroTarjeta { get; set; }
    }
}
