//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaChequesPropios
    {
        public long NroCheque { get; set; }
        public decimal MontoCheque { get; set; }
        public string ApellidoyNombre { get; set; }
        public int NroPago { get; set; }
        public string FechaEmision { get; set; }
        public string FechaCobro { get; set; }
        public string Cruzado { get; set; }
        public string Banco { get; set; }
        public string FechaBaja { get; set; }
        public int IdCheque { get; set; }
        public bool Propio { get; set; }
    }
}
