//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRemitosCompraCab
    {
        public int IdRemitoCompra { get; set; }
        public string NroRemito { get; set; }
        public int NroProveedor { get; set; }
        public string Observaciones { get; set; }
        public string ApellidoyNombre { get; set; }
        public string FechaRemitoCompra { get; set; }
        public string NroFactura { get; set; }
        public Nullable<int> IdFacturaCompra { get; set; }
        public short IdEmpresa { get; set; }
    }
}
