//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRemitosCompraDet
    {
        public int IdRemitoCompra { get; set; }
        public long IdArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public string DescCorta { get; set; }
        public string UMedida { get; set; }
        public int Total { get; set; }
    }
}
