//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaClientes
    {
        public int NroCliente { get; set; }
        public string ApellidoyNombre { get; set; }
        public string TipoDocumento { get; set; }
        public string Nro_Doc { get; set; }
        public string Direccion { get; set; }
        public string Descripcion { get; set; }
        public string Localidad { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Provincia { get; set; }
        public string Cuit { get; set; }
        public string FechaBaja { get; set; }
        public string Comentario { get; set; }
        public short CodigoPostal { get; set; }
        public string Descipcion { get; set; }
        public int ClienteCajaDistribucionServicioId { get; set; }
        public string Estado { get; set; }
    }
}
