//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCuentasBancarias
    {
        public int IdCuentaBancaria { get; set; }
        public int IdBanco { get; set; }
        public string TitularCuenta { get; set; }
        public string CBU { get; set; }
        public long NroCuenta { get; set; }
        public byte IdEmpresa { get; set; }
        public string Descripcion { get; set; }
    }
}
