//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaNCCompSinSaldar
    {
        public int IdFacturaCompra { get; set; }
        public int NroProveedor { get; set; }
        public string NroFactura { get; set; }
        public short IdEmpresa { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> TotalSaldado { get; set; }
        public Nullable<decimal> Pendiente { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> IdNotaCredito { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Direccion { get; set; }
        public short IdTipoFactura { get; set; }
    }
}
