//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaMovimientosCaja
    {
        public string TipoMov { get; set; }
        public string NroFact { get; set; }
        public string TipoPago { get; set; }
        public string DescripcionMov { get; set; }
        public System.DateTime FechaMov { get; set; }
        public Nullable<decimal> Ingreso { get; set; }
        public Nullable<decimal> Egreso { get; set; }
        public int IdAperturaCaja { get; set; }
        public long IdMovimientoCaja { get; set; }
        public string FechaBaja { get; set; }
    }
}
