//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDatosImpositivos
    {
        public int NroCliente { get; set; }
        public Nullable<System.DateTime> FechaInicioExc { get; set; }
        public string Descripcion { get; set; }
        public string Provincia { get; set; }
        public int NroInscripcion { get; set; }
        public string Tipo { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public string NroCertificadoExc { get; set; }
        public Nullable<System.DateTime> FechaFinExc { get; set; }
        public int IdDatosImpositivos { get; set; }
    }
}
