//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaTotalesCancelacionPagos
    {
        public int NroProveedor { get; set; }
        public int IdPago { get; set; }
        public decimal MontoTotal { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal MontoPagado { get; set; }
        public Nullable<decimal> MontoDisponible { get; set; }
    }
}
