//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDetallePagoCancelacion
    {
        public int IdCancelacion { get; set; }
        public int idpago { get; set; }
        public int IdFacturacompra { get; set; }
        public string NroComp { get; set; }
        public int NroProveedor { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> TotalSaldado { get; set; }
        public decimal MontoCancelacion { get; set; }
        public System.DateTime FechaEmision { get; set; }
    }
}
